version: '3.9'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nest-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
